image: tnewton1/mkdocs-build:v1

stages:
  - deploy

Build and Upload:
    stage: deploy
    script:
        - mkdocs build
        # - cp -rT web-server-files site
        - lftp -u $FTP_USERNAME,$FTP_PASSWORD -e "set ftp:list-options -a; mirror --reverse --verbose --delete site/ public_html/; bye"
