#image: tnewton1/mkdocs-build:v1
image: ubuntu:latest

stages:
  - deploy

Build and Upload:
    stage: deploy
    script:
        - apt update
        - apt upgrade -y
        - pip install --upgrade pip
        - pip install mkdocs
        - pip install mkdocs-material
        - pip install neoteroi-mkdocs
        - mkdocs build
        - lftp --version
        # - cp -rT web-server-files site
        - lftp -e "set ssl:verify-certificate no; open learn.nodespace.com; user $FTP_USERNAME $FTP_PASSWORD; set ftp:list-options -a; mirror --reverse --verbose --delete site/ public_html/; bye"
