site_name: NodeSpace Learn
site_description: NodeSpace Learn is a collection of guides and tutorials for NodeSpace customers.
site_author: NodeSpace Technologies, LLC
site_url: https://learn.nodespace.com
use_directory_urls: false
copyright: "Copyright &copy; NodeSpace Technologies, LLC"

theme:
  name: material
  custom_dir: overrides
  logo: assets/nodespace-learn.png
  font:
    text: 'Red Hat Text'
    code: 'Red Hat Mono'
  features:
    - navigation.tabs
    - navigation.top
    # - toc.integrate
  palette:
    scheme: nodespace

extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/extra.css

plugins: 
  - search


markdown_extensions:
  - toc:
      baselevel: 4
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink
  - neoteroi.cards
  - tables
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://nodespace.social/@nodespace
      name: nodespace on Mastodon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nodespace
      name: nodespace on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/nodespacehosting
      name: nodespace on GitHub
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/nodespacetech
      name: nodespace on Facebook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nodespace
      name: nodespace on LinkedIn

nav:
  - NodeSpace Home: https://www.nodespace.com
  - Learn Home:
    - Home: index.md
    - Hosting Services: hosting/index.md
    - Account &amp; Billing: account/index.md
    - Dedicated &amp; Virtual Servers: servers/overview.md
  - Account &amp; Billing:
    - Account &amp; Billing: account/index.md
    - Billing Overview: account/billing.md
  - Hosting Services:
    - Overview: hosting/index.md
    - Why we don't offer "Unlimited" plans: hosting/unlimited.md
    - Shared Hosting: 
      - Shared Hosting Overview: hosting/shared/overview.md
      - Frequently Asked Questions: hosting/shared/faq.md
      - Website Transfers:
        - hosting/shared/self-transfer.md
      - How to check your usage: hosting/shared/check-usage.md
      - SSL Certificates:
        - How multi-year SSL certificates work: hosting/shared/ssl/multi-year.md
      - MultiPHP vs PHP Selector: hosting/multiphp-vs-php-selector.md
    - Reseller Hosting: hosting/reseller/overview.md
    - WordPress Hosting: hosting/wordpress/overview.md
  - Dedicated &amp; Virtual Servers:
    - Overview: servers/overview.md
    - Dedicated Servers: 
      - servers/dedicated/overview.md
      - Provisioning: servers/dedicated/provisioning.md
    - Virtual Private Servers: 
      - servers/vps/overview.md
    - Networking:
      - servers/networking/public.md
      - servers/networking/private.md
    - Operating Systems: 
      - servers/operating_systems.md
      - servers/operating_systems/almalinux.md
      - servers/operating_systems/centos.md
      - servers/operating_systems/debian.md
      - servers/operating_systems/fedora.md
      - servers/operating_systems/freebsd.md
      - servers/operating_systems/ubuntu.md


      
